### ISSUE TITLE
Which ecoprovince is Race Rocks in?

### ISSUE THREAD

**Issue by joethorley** [bcgov/cccharts#10]
Lat 48.18, Long -123.32

For some reason it is not falling in an ecoprovince from bcmaps.

**Comment by ateucher** [comment]
I guess we'd better call it Georgia Depression:

``` r
library(bcmaps)
plot(spTransform(ecoprovinces, CRS("+init=epsg:4326")))
rr <- data.frame(x = -123.32, y = 48.14)
coordinates(rr) <- ~x+y
plot(rr, add = TRUE, col = "red", cex = 15)
```

![capture](https://cloud.githubusercontent.com/assets/2816635/19008168/2518a09e-871e-11e6-8a28-435fad3b027d.PNG)
