### ISSUE TITLE
River flow with raw data

### ISSUE THREAD

**Issue by joethorley** [bcgov/cccharts#17]

**Comment by joethorley** [comment]
Check licensing for data

**Comment by joethorley** [comment]
@ateucher and @stephhazlitt  In order to plot the trends with the raw data - I need to know how the data was centered i.e. the intercept value is not for 0 BCE but some year between 1900 and 2015 and it may differ by data set.

**Comment by ateucher** [comment]
Does the `start_year` column in the results dataset not give you what you need?

**Comment by joethorley** [comment]
Good thinking - I'll check it out!

**Comment by joethorley** [comment]
That works

**Comment by joethorley** [comment]
@ateucher - next question - some of the flow timing data appears erroneous (see below)

Is there any way to determine which was included in the analysis?

![rplot](https://cloud.githubusercontent.com/assets/613671/19541431/2513dbb6-961b-11e6-9ed4-fa92cf6dd989.png)

**Comment by ateucher** [comment]
Hmmmm... ok thanks. I'll have a look

**Comment by joethorley** [comment]
@ateucher We need a way to determine which data points were included in the analysis

**Comment by ateucher** [comment]
@joethorley they were all included. The Mann-Kendall test was chosen because it is highly robust to outliers.

**Comment by joethorley** [comment]
Thanks!
