### ISSUE TITLE
SST: Why are Departure Bay and Entrance island so diff but close together?

### ISSUE THREAD

**Issue by joethorley** [bcgov/cccharts#38]

**Comment by joethorley** [comment]
for SST

**Comment by stephhazlitt** [comment]
From the [report (page 33)](http://www2.gov.bc.ca/assets/gov/environment/research-monitoring-and-reporting/reporting/envreportbc/archived-reports/climate-change/climatechangeindicators-13sept2016_final.pdf) "Departure Bay is in a location of limited tidal mixing and strong influences from nearby freshwater outfalls. Other nearby stations, such as Entrance Island, are more exposed to the Strait of Georgia where substantial tidal mixing and exposure to Fraser River waters occurs that minimize other local effects."
