### ISSUE TITLE
Add comments on data sources in data-raw scripts

### ISSUE THREAD

**Issue by ateucher** [bcgov/cccharts#8]
In a comment in each of the data-raw scripts, can you add a link to the data catalogue record page and mention the license it is under (OGL-BC in most cases)? Or in a README in the data-raw folder?

**Comment by joethorley** [comment]
We could add it to the R documentation for each data set?

**Comment by ateucher** [comment]
That would be great. But a one-line comment in the source code would be helpful as well.

**Comment by joethorley** [comment]
Done
