### ISSUE TITLE
Flow station data Uncertainty Information.

### ISSUE THREAD

**Issue by joethorley** [bcgov/cccharts#9]
As far as I can determine there is no uncertainty information for confidence intervals in the flow station data at https://catalogue.data.gov.bc.ca/dataset/d6f30634-a6a8-45b5-808e-210036f25044/resource/eecc311c-2e5b-4bec-8d0a-ae5f1956dffe/download/bcriverflowtimingvolumetrends.csv

Can you confirm this is the case or add if missing.

Thanks

Joe

**Comment by ateucher** [comment]
We'll update that file with uncertainty information and other data relevant to the tests - the file structure will change (for the better), so I'd advise holding off on doing too much with this right now.

**Comment by ateucher** [comment]
Hi @joethorley, I've updated the data at that link including confidence intervals.

Let me know if you have any questions about it.
